// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqkpflrpfgenaolmypyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxa3BmbHJwZmdlbmFvbG15cHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzIzNzEsImV4cCI6MjA2MDQwODM3MX0.xReKgAU7VIq5RAOR39u3DML8gNNsX9dY6GVqkIwoWH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);